#server:
#  port: 8090
#spring:
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password: ''
#  h2:
#    console:
#      enabled: true
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#  config:
#    import:
#      - "loans-qa.yml"
#      - "loans-prod.yml"
#  profiles:
#    active:
#      - "prod"


build:
  version: "3.0"


loans:
  message: "Welcome to loans service"
  contact:
    name: "Ahmad Mahmoud"
    email: "ahmad.mahmoud@gmail.com"
  onCallSupport:
    - (321) 354-546
    - (452) 546-981
